# Generated by Django 3.1 on 2020-08-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20200821_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.checklistpoint')),
                ('eplan_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.eplandevice')),
            ],
        ),
        migrations.AddField(
            model_name='eplandevice',
            name='selected_checklist_points',
            field=models.ManyToManyField(through='checklists.SelectedCheckpoint', to='checklists.ChecklistPoint'),
        ),
    ]
