# Generated by Django 3.1 on 2020-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_project_eplan_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='eplan',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
