# Generated by Django 3.1 on 2020-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_project_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eplan',
            old_name='status',
            new_name='device_count',
        ),
        migrations.AddField(
            model_name='eplan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
