# Generated by Django 3.1 on 2020-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_auto_20200825_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='eplandevice',
            name='checkpoint_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eplandevice',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
