# Generated by Django 3.1 on 2020-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_auto_20200828_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistpoint',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistpoint',
            name='user_verified',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='selectedcheckpoint',
            name='user_verified',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
